#include <sstream>
#include <fstream>
#include <numeric>
#include <configuration.hpp>
#include <boost/lambda/lambda.hpp>
#include <boost/lambda/bind.hpp>
#include <boost/numeric/ublas/matrix.hpp>
#include <boost/numeric/ublas/io.hpp>
#include <boost/numeric/ublas/vector_proxy.hpp>
#include <boost/algorithm/string.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/regex.hpp>
#include <boost/format.hpp>
#include <boost/foreach.hpp>
#include <boost/graph/graphviz.hpp>
#include <factory/factory.h>
#include <matlab_io.hpp>
#include "sdf_graph.hpp"

